name: Deploy to MonsterASP

on:
  push:
    branches: [ "main" ] # deployment will be triggered on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: windows-latest # use Windows runner for WebDeploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x # specify your .NET version

      - name: Publish Project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to MonsterASP
        run: |
          msdeploy.exe -verb:sync -source:contentPath='${{ github.workspace }}/publish' -dest:contentPath='${{ secrets.WEBSITE_NAME }}',ComputerName='${{ secrets.SERVER_COMPUTER_NAME }}',UserName='${{ secrets.SERVER_USERNAME }}',Password='${{ secrets.SERVER_PASSWORD }}',AuthType='Basic' -enableRule:AppOffline